CREATE TABLE CREDIT_CARD_DETAILS (ID NUMBER PRIMARY KEY,CUST_ID NUMBER, CARD_NUMBER VARCHAR2(25) NOT NULL,AMOUNT_LIMIT VARCHAR2(25) NOT NULL, BALANCE VARCHAR2(25) NOT NULL);

CREATE SEQUENCE CREDITCARD_SEQ START WITH 1 INCREMENT BY 1;

ALTER TABLE "CREDIT_CARD_DETAILS" ADD CONSTRAINT "FK_CREDIT_CARD_DETAILS_TO_CREDIT_CARD_CUSTOMER" FOREIGN KEY("CUST_ID") REFERENCES "CREDIT_CARD_CUSTOMER" ("ID");